# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-ast
    - id: check-executables-have-shebangs
    - id: check-symlinks
    - id: debug-statements
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black

- repo: local
  hooks:

    - id: poetry-check
      name: poetry
      entry: poetry check
      language: system
      files: ^(.*/)?pyproject.toml$
      pass_filenames: false

    - id: poetry-lock
      name: poetry-lock
      entry: poetry lock  --no-update
      language: system
      pass_filenames: false

    - id: mypy
      name: mypy
      entry: poetry run mypy
      language: system
      pass_filenames: false

    - id: ruff
      name: ruff
      entry: poetry run ruff peewee_aio
      language: system
      pass_filenames: false

    - id: pytest
      name: pytest
      entry: poetry run pytest tests
      language: system
      pass_filenames: false
